bfm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bookkeeping.urls')),
    path('admin/', admin.site.urls),
    path('bookkeeping/', include('bookkeeping.urls')),
]

bookkeeping/urls.py
from django.urls import path, include

from .views import account_create
from .views import upload_accounts_csv
from .views import AccountListView
from .views import bookkeeping_main

urlpatterns = [
    path('', bookkeeping_main, name='bookkeeping_main'),
    path('account/create/', account_create, name='account_create'),
    path('account/create/upload', upload_accounts_csv, name='account_upload'),
    path('account/list/', AccountListView.as_view(template_name="bookkeeping/account/account_list.html") , name='account_list'),
]

bookkeeping/models.py
import io
import csv
from django.db import models

# Create your models here.
class Account(models.Model):
    """
    the Account class describes a parent model table which all accounts will
    be its subclass. Any account can be considred to be one the following types:
        - Asset
        - Liability
        - Income
        - Expense
        - Capital
    """
    ASSET='AS'
    LIABILITY='LB'
    CAPITAL="CP"
    INCOME='IN'
    EXPENSE='EX'
    ACCOUNT_TYPE_CHOICES = [
        (ASSET, 'Assets'),
        (LIABILITY, 'Liability'),
        (CAPITAL,'Capital'),
        (INCOME, 'Income'),
        (EXPENSE, 'Expense'),
    ]
    FIXED_ASSET = 'AS/FX'
    INTANGIBLE_ASSET = 'AS/IT'
    CURRENT_ASSET = 'AS/CR'
    ACCOUNT_CATEGORY_CHOICES = [
        (FIXED_ASSET, 'Fixed Asset'),
        (CURRENT_ASSET, 'Current Asset'),
        (INTANGIBLE_ASSET, "Intagible Asset"),
    ]

    account_type = models.CharField(
        max_length=2,
        choices=ACCOUNT_TYPE_CHOICES,
        null=False,
        blank=False,
        default=ASSET
    )

    account_name = models.CharField(
        max_length=128,
        null=False,
        blank=False,
        unique=True,
        primary_key=True
    )

    account_description = models.CharField(
        max_length=255,
        null=False,
        blank=True,
        default=f'a new account'
    )

    account_category = models.CharField(
        max_length=9,
        null=True,
        blank=True,
        choices=ACCOUNT_CATEGORY_CHOICES
    )

    def isAsset(self):
        return True if (self.account_type == self.ASSET) else False

    def isLiability(self):
        return True if (self.account_type == self.LIABILITY) else False
    
    def isIncome(self):
        return True if (self.account_type == self.INCOME) else False
    
    def isExpense(self):
        return True if (self.account_type == self.EXPENSE) else False

    def __str__(self):
        return f'{self.account_name} --- {self.account_type}'
    
    def _create_object_from_dictionary(self, row, update=True):
        try:
            obj, created = Account.objects.get_or_create(
                            account_name = row['account_name'],
                            account_type = row['account_type'],
                            account_category = row['account_category'],
                            account_description = row['account_description'],
                        )
            if created is False:
                obj.save()
        except:
            obj = Account.objects.get(account_name=row['account_name'])
            obj.account_type = row['account_type']
            obj.account_category = row['account_category']
            obj.account_description = row['account_description']
            if update is True:
                obj.save()
        return obj

    def fill_from_csv(self, from_memory=True, file_in_memory=None, file_path="bookkeeping/accounts.csv"):
        if from_memory is True:
            if file_in_memory is None:
                raise ValueError("When csv file is read from memeory the file_in_memory arg must be given")        
            for chunk in file_in_memory.chunks():
                csv_file_string = chunk.decode("utf-8")
                csv_file_in_memory = io.StringIO(csv_file_string)
                reader = csv.DictReader(csv_file_in_memory, delimiter=',', quotechar='|')
                for row in reader:
                    self._create_object_from_dictionary(row)
        else:
            with open(file_path, newline='') as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                        self._create_object_from_dictionary(row)

bookkeeping/forms.py
from django import forms
from django.forms import ModelForm
from .models import Account

class AccountUploadFileForm(forms.Form):
    file = forms.FileField()

class AccountCreateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["account_name", "account_type", "account_category", "account_description"]
        widgets = {
            "account_description": forms.Textarea,
            "account_name": forms.TextInput,
            "account_type": forms.RadioSelect,
        }

bookkeeping/views.py
import csv
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView
from bookkeeping.models import Account
from .forms import AccountUploadFileForm
from .forms import AccountCreateForm

# Create your views here.
def account_create(request):
    """The functions creates an account by handling the request
    """
    if request.method == 'GET':
        form = AccountCreateForm()
        context={"form":form}
        return render(request, 'bookkeeping/account/account_create.html',context=context)
    if request.method == 'POST':
        form = AccountCreateForm(request.POST)
        if form.is_valid():
            account = Account()
            account.account_name = form.cleaned_data['account_name']
            account.account_type = form.cleaned_data['account_type']
            account.account_category = form.cleaned_data['account_category']
            account.account_description = form.cleaned_data['account_description']
            account.save()
            form = AccountCreateForm()
        return HttpResponseRedirect('../list')
    

# a list view of accounts
class AccountListView(ListView):
    model = Account
    paginate_by = 10  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

# a view to upload accounts
def upload_accounts_csv(request):
    account = Account()
    if request.method == 'POST':
        form = AccountUploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file_in_memory = request.FILES['file']
            account.fill_from_csv(file_in_memory=file_in_memory)
            return HttpResponseRedirect('../list')
    else:
        form = AccountUploadFileForm()
    return render(request, 'bookkeeping/account/account_upload.html', {'form': form})

def bookkeeping_main(request):
    return render(request, 'bookkeeping/account/main.html', {})

bookkeeping/templates/bookkeeping/account/account_base.html
{% extends 'base.html' %}
{% block header %}
	<div class="row d-flex justify-content-between">
	<div class="col-8">
		<h1 class="h1">Account</h1>
	</div>
	<div class="col-4 aml-auto p-2 d-flex justify-content-end">
		<a href={% url 'bookkeeping_main' %}>Main</a>
	</div>
	</div>
	<h2 class="h5">
		{% block account-header %}
		{% endblock account-header %}
	</h2>
{% endblock header %}


{% block  content %}
{% endblock  %}

bookkeeping/templates/bookkeeping/account/account_create.html
{% extends 'bookkeeping/account/account_base.html' %}

{% load crispy_forms_tags %}

{% block account-header %}
Create
{% endblock account-header %}

{% block  content %}
    <form method = "post"  action={% url 'account_create' %} class="form-group"> 
        {% csrf_token %}
        <div class="form-row d-flex justify-content">
            <div class="form-group col-12 mb-0 px-2">
                {{ form.account_name|as_crispy_field }}
                {{ form.account_name.error }}
            </div>
        </div>
        <div class="form-row d-flex justify-content">
            <div class="form-group col-md-6 mb-0 px-2">
                {{ form.account_type|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0 px-2">
                {{ form.account_category|as_crispy_field }}
            </div>
        </div>
        <div class="form-row d-flex justify-content">
            <div class="form-group col-12 mb-0 px-2">
                {{ form.account_description|as_crispy_field }}
            </div>
        </div>
        <br>
        <button class='btn btn-primary' type="submit">Create Account</button> 
    </form> 
{% endblock  %}

bookkeeping/templates/bookkeeping/account/account_list.html
{% extends 'bookkeeping/account/account_base.html' %}

{% block account-header %}
Accounts List
{% endblock account-header %}

{% block  content %}
	<table class="table table-striped">
		<thead class="table-dark">
			<tr>
			<th scope="col">#</th>
			<th scope="col">Account Name</th>
			<th scope="col">Type</th>
			<th scope="col">Category</th>
			<th scope="col">Description</th>
			</tr>
		</thead>
  		<tbody>


	{% for account in page_obj %}
		    <tr class='small'>
				<th scope="row">{{ forloop.counter }}</th>
				<td>{{ account.account_name }}</td>
				<td>{{ account.get_account_type_display }}</td>
				<td>{{ account.get_account_category_display }}</td>
				<td>{{ account.account_description }}</td>
			</tr>
	{% empty %}
		<li>No accounts yet.</li>
	{% endfor %}
		</tbody>
	</table>


	</div>
	<nav aria-label="pagination Page navigation example">
		<span class="step-links">
			<ul class="pagination justify-content-center">
				{% if page_obj.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page=1" tabindex="-1">&laquo; first</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
					</li>
				{% endif %}
				{% if page_obj.num_pages > 1%}
					<li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
				{% endif %}
				{% if page_obj.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
					</li>
				{% endif %}
			</ul>
		</span>
	</nav>	
{% endblock  %}

bookkeeping/templates/bookkeeping/account/account_upload.html
{% extends 'bookkeeping/account/account_base.html' %}

{% block account-header %}
Upload Account List
{% endblock account-header %}


{% block  content %}
    <form method = "post" enctype="multipart/form-data" class="form-group"> 
        {% csrf_token %}
        Accounts CSV File: <div class="form-control">{{ form.file }}</div>
        <br>
        <button class='btn btn-primary' type="submit">Upload</button> 
    </form> 
{% endblock  %}

bookkeeping/templates/bookkeeping/account/create.html
{% extends 'bookkeeping/account/account_base.html' %}

{% block account-header %}
Create
{% endblock account-header %}

{% block  content %}
	   {% if Hello %}
	   	{% for item in Hello %}
		   <p>{{ item }}</p>
		{% endfor %}
	   {% else %}
	   <p>Nothing to show</p>
	   {% endif %}
{% endblock  %}

bookkeeping/templates/bookkeeping/account/main.html
{% extends 'bookkeeping/account/account_base.html' %}

{% block account-header %}
Bookkeeping Home
{% endblock account-header %}


{% block content %}
<ul>
    <li>
        <a href={% url 'account_create' %}>Create Account</a>
    </li>
    <li>
        <a href={% url 'account_upload' %}>Upload Accounts</a>
    </li>
    <li>
        <a href={% url 'account_list' %}>List of Accounts</a>
    </li>
</ul>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>{</title>
  </head>
  <body>
    <div class="header p-2 m-0 bg-dark text-light">
      {% block header %}
      {% endblock header %}
    </div>
    <div class="container m-5">
        {% block content %}
        {% endblock content %}
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </body>
</html>